### ISSUE TITLE
[Feature request] Please add the function to modify the source file

### ISSUE THREAD

**Issue by ciallowo** [sethyuan/logseq-plugin-charspacing#1]
Just like obsidian's [Pangu](https://github.com/Natumsol/obsidian-pangu) plugin.

**Comment by sethyuan** [comment]
我调研一下看 Logseq 的插件机制是否能实现的了。

**Comment by sethyuan** [comment]
实现了，v1.1.0，你可以更新下试试看。不过还是建议先看下README，直接修改源文件还是有风险的。 @ciallowo

**Comment by ciallowo** [comment]
> 实现了，v1.1.0，你可以更新下试试看。不过还是建议先看下 README，直接修改源文件还是有风险的。 @ciallowo

Thank you, I noticed the danger of what you said, but this does not hinder it is a good function.

**Comment by ciallowo** [comment]
Thank you for what you have done, and I will close this issue.

**Comment by sethyuan** [comment]
@ciallowo I already found bugs with the overwrite mode, there're several cases where text would be replaced wrong. The replacing of the original content is way more complex than I thought. I've removed this functionality for the time being, **I recommend you not to use it neither**.

Reasoning: Logseq supports multiple input formats (markdown, org-mode, html, hiccup), it would be too complicated to handle text transformations in all these cases. There are also corner cases where replacing is not desirable, such as in hyperlinks, source blocks, etc.

**Comment by ciallowo** [comment]
> @ciallowo I already found bugs with the overwrite mode, there're several cases where text would be replaced wrong. The replacing of the original content is way more complex than I thought. I've removed this functionality for the time being, **I recommend you not to use it neither**.
> 
> Reasoning: Logseq supports multiple input formats (markdown, org-mode, html, hiccup), it would be too complicated to handle text transformations in all these cases. There are also corner cases where replacing is not desirable, such as in hyperlinks, source blocks, etc.

I see... I wish I could help, but I am not a programmer, I will upgrade the plugin in time, thank you for your reminder.
