### ISSUE TITLE
关于代码块显示效果的一些问题

### ISSUE THREAD

**Issue by PaperKite233** [sethyuan/logseq-plugin-charspacing#11]
1. 部分时候代码块中英文之间没有添加空格，见图aaa、bbb对比
2. 代码块中英文添加空格之后，光标移动有问题，表现为无法成功将光标定位到行末、在光标处添加文字与实际光标位置不符合，见图ccc效果，测试时是紧挨着ccc后输入123
3. 代码块空格不会立即生效，需要两次esc切换才行

<img width="749" alt="pic" src="https://user-images.githubusercontent.com/34703198/207521246-016175b3-74bd-434a-9171-10a9746b9d05.png">

**Comment by sethyuan** [comment]
嗯，code block里不应该添加空格，和inline code是一个道理。我看看把code block里的禁止掉。

**Comment by sethyuan** [comment]
@PaperKite233 Fix了，请试用下新版本。

**Comment by PaperKite233** [comment]
符合预期，感谢
