### ISSUE TITLE
开启插件后影响checkbox勾选

### ISSUE THREAD

**Issue by PaperKite233** [sethyuan/logseq-plugin-charspacing#12]
logseq版本0.8.15
插件版本最新
开启插件后，只能勾选纯中文checkbox，效果如下图所示
可复现

<img width="258" alt="image" src="https://user-images.githubusercontent.com/34703198/210748718-866d4ccf-b34e-4202-8bb6-9b20a072e2e2.png">

测试markdown：
```
- 当插件开启时测试 checkbox  
	* [ ] 中文english
	* [ ] english中文
	* [ ] english
	* [X] 中文中文
- 当插件关闭时测试 checkbox  
	* [X] 中文english
	* [X] english中文
	* [X] english
	* [X] 中文中文
```

**Comment by sethyuan** [comment]
这是Logseq本身对checkbox的语法支持不佳导致的，本质上Logseq中不鼓励用markdown的checkbox语法，建议用标准的task来做。

我试了一下，必须得有前面那个`*`才能渲染出checkbox，这个场景太小众了，暂时不予处理。要处理也只能屏蔽对checkbox的空格处理。

**Comment by PaperKite233** [comment]
好的，了解了
