### ISSUE TITLE
效果可能受到latex语句的干扰？

### ISSUE THREAD

**Issue by SkywingsWang** [sethyuan/logseq-plugin-charspacing#13]
例：
input: 广告商$j$的预期成本/提供商的利润
output: 广告商 j的预期成本/提供商的利润
只有第一个空格生效了，第二个没有，会紧贴后半个语句

**Comment by sethyuan** [comment]
我看看兼容一下。

**Comment by sethyuan** [comment]
发了一版，兼容了inline math。
