### ISSUE TITLE
大神 namespace 之间的 / 能加宽吗？

### ISSUE THREAD

**Issue by hillsmao** [sethyuan/logseq-plugin-charspacing#14]
<img width="362" alt="image" src="https://github.com/sethyuan/logseq-plugin-charspacing/assets/107061250/ab1d14a9-fd76-49e4-9bd3-b1d08715ae8a">

**Comment by sethyuan** [comment]
应该是可以的，不过效果不一定好，比如你给的例子里会展示成这样： `供应链 / 产品规划 / 解决方案 / leads`。另外charspacing只作用于中英文及符号之间，像 `Hello/World` 这样的就不会有空格了。

这个效果是你想要的吗？如果是的话我可以加个选项。

**Comment by hillsmao** [comment]
> 应该是可以的，不过效果不一定好，比如你给的例子里会展示成这样： `供应链 / 产品规划 / 解决方案 / leads`。另外charspacing只作用于中英文及符号之间，像 `Hello/World` 这样的就不会有空格了。
> 
> 这个效果是你想要的吗？如果是的话我可以加个选项。

要的！

**Comment by sethyuan** [comment]
@hillsmao 加上了，插件设置里添加了一个选项，开启后重启下Logseq。

**Comment by hillsmao** [comment]
太舒服了！
