### ISSUE TITLE
Latex文本与汉字之间缺少空格

### ISSUE THREAD

**Issue by HaomingFu** [sethyuan/logseq-plugin-charspacing#16]
## 问题：
如果latex文本的第一个字符不是英文字母和数字字符时，如\alpha, \beta等，那么该latex文本与其前面的汉字之间缺少空格，如图。
![image](https://github.com/sethyuan/logseq-plugin-charspacing/assets/7111769/261fd815-e5d0-4d5f-89d9-f05868acb1ba)

## 复现步骤：
1. 在logseq的某个block上输入：前面文字$\alpha = \beta$后面文字。
2. 那么可以观察到排版“前面文字”与“$\alpha$”之间缺少空格。

## 补充说明：
在我的实验中，latex文本与其后面的汉字之间总是有空格的，latex文本第一个字符是字母或数字时，它与前面的汉字之间也有空格。

## 期望的效果：
不管latex文本是什么，更具体来说，不管latex文本的第一个字符是什么，latex文本与其前面的汉字之间在排版时有个空格。

**Comment by sethyuan** [comment]
这个间隔我看了一下，是Logseq本身的行为，但是它只空了右边的，没有空出左边的。我觉得这个不应该在Char Spacing中改，应该是Logseq把左边的间隔也补起。不过你可以在`custom.css`中自己加入下面这段CSS来解决：

```css
.latex-inline {
  margin-left: 0.4ch;
}
```

**Comment by HaomingFu** [comment]
> 这个间隔我看了一下，是Logseq本身的行为，但是它只空了右边的，没有空出左边的。我觉得这个不应该在Char Spacing中改，应该是Logseq把左边的间隔也补起。不过你可以在`custom.css`中自己加入下面这段CSS来解决：
> 
> ```css
> .latex-inline {
>   margin-left: 0.4ch;
> }
> ```

谢谢你的解答
