### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by artemith** [sethyuan/logseq-plugin-charspacing#2]
![图片](https://user-images.githubusercontent.com/14881525/146660606-ae0f9386-a6d9-4ee0-9acf-7ff515ca2d76.png)
代理开全局模式也不行

**Comment by sethyuan** [comment]
这是墙的问题。你的全局代理应该没起作用，我一会儿放个release到Gitee上，到时候你可以下载下来本地加载插件。

**Comment by sethyuan** [comment]
@artemith https://gitee.com/sethyuan/logseq-plugin-charspacing/releases

下载解压后在Logseq插件页面通过本地加载那个按钮选择解压后的文件夹就可以了。

![load](https://user-images.githubusercontent.com/3410293/146664093-173c6312-3bc4-4f9f-8ce9-48538b2a5fc5.png)
