### ISSUE TITLE
最好能支持行内代码

### ISSUE THREAD

**Issue by vipzhicheng** [sethyuan/logseq-plugin-charspacing#3]
![image](https://user-images.githubusercontent.com/1209538/147445914-e280da03-f065-4074-a504-f598c7178ca7.png)

这个插件很不错，我之前想是不是做一个命令只写修改原文，你这个可以不改原文是更好的方案。

**Comment by sethyuan** [comment]
哈哈，感谢大佬夸奖！至于inline code这种，代码是不处理的，它里面的中英文不应该被自动分割，例如`http://a.com/q=中国people`，这里”中国“和”people“不应该被分割开。其实我觉得你想要的应该是给code两边加个margin的样式，而不是加空格。我也考虑过，但是目前的code已经有不小的padding了，再加margin感觉不是很好看了。

**Comment by sethyuan** [comment]
![image](https://user-images.githubusercontent.com/3410293/147515840-e5dd384e-c28e-4905-9091-c40f270b9b90.png)

这种是不是你想要的效果呢？就是中文和中文间只要也是这种带背景色性质的就都要加空格。

**Comment by sethyuan** [comment]
> inline code两边如果没有空格的话就给它加上，无论是否存在中英文字符的情况。

已经根据这个逻辑调整了，更新了版本。

**Comment by vipzhicheng** [comment]
是我想要的效果，我可能更倾向于 inline code 和 highlight 都加上空格，不过这是个人偏好，仅供参考，感谢更新 👍

**Comment by sethyuan** [comment]
好的，那我就把这个issue关掉了。
