### ISSUE TITLE
在块被引用后，在引用的位置会再次添加空格

### ISSUE THREAD

**Issue by XinLi0111** [sethyuan/logseq-plugin-charspacing#4]
![image](https://user-images.githubusercontent.com/31495943/147904740-a88b1955-32b9-4ec1-a31b-881a6d4a7962.png)

**Comment by sethyuan** [comment]
能提供一下这块你使用的markdown吗？我自己造了一个没能复现。

**Comment by XinLi0111** [comment]
这是原始内容：
TODO `tbl2asn`的使用以及数据上传

我测试了下想到的情况，只有在TODO/DOING 后的第一个代码块后会出现多余的空白
![image](https://user-images.githubusercontent.com/31495943/147946760-566f6256-36ff-4095-a871-099c85ca4945.png)

**Comment by sethyuan** [comment]
@XinLi0111  问题已解决，我发布了新版本，请尝试。

**Comment by XinLi0111** [comment]
已解决，感谢！！
