### ISSUE TITLE
添加对 Org-Mode 的支持

### ISSUE THREAD

**Issue by ATNewHope** [sethyuan/logseq-plugin-charspacing#5]
这是个好插件，不需要手动打空格了。不过我发现这仅适用于 Markdown，而不适用于 Org-Mode，不知道作者是否有可能添加一下支持呢？非常感谢！

**Comment by sethyuan** [comment]
理论上插件的实现和你所用的语法应该是无关的，可能org-mode有什么特别的实现。目前我没有精力维护对org-mode的支持，要是你能提供PR的话我是非常欢迎的。

**Comment by ATNewHope** [comment]
我也想提供 PR，但是目前我还不会编程，只是会 LaTeX 以及一些简单的 bash 罢了。
向您请教一下，为这个插件写 PR 需要学习哪些知识（比如编程语言）呢？

**Comment by ATNewHope** [comment]
那个，抱歉我弄错了，我前两天把所有笔记从Markdown迁移到Org-mode的过程中发现Org-mode中没有自动空格样式，但其实其它的很多插件也都用不了了（比如heatmap，Focus-mode等），这应该是logseq自己的bug。刚才把插件卸载重装了一遍就成功了，org-mode也能用。
