### ISSUE TITLE
中文日期可以配置开关不加空格

### ISSUE THREAD

**Issue by willzhqiang** [sethyuan/logseq-plugin-charspacing#7]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/279170/169672149-19765562-aa02-47e9-8f61-8722cc486333.png">
如图，我的日期选择的是年月日这种，我看默认也处理了，但是感觉这个是不是紧凑在一起更合适？

**Comment by sethyuan** [comment]
目前没有特别好的方法做这么精细的处理，另外对于哪种更美观也是见仁见智。

**Comment by willzhqiang** [comment]
> 

是的，现在看习惯了，我觉得分开也挺好的😂
