### ISSUE TITLE
TODO,WAITING等关键字之后可不可以不要加入空格

### ISSUE THREAD

**Issue by shiyuanyou** [sethyuan/logseq-plugin-charspacing#8]
<img width="187" alt="截屏2022-08-31 15 36 32" src="https://user-images.githubusercontent.com/58103392/187620391-e0947f1e-2cd8-45f7-b09e-7f00d031d373.png">
如图，这里的中文和英文在同一个todo list下，显得很不齐。请问有办法解决吗

**Comment by sethyuan** [comment]
解决了，我发了个新版本，你可以尝试一下。
