### ISSUE TITLE
[Feature request] Add a space between Japanese and Latin characters

### ISSUE THREAD

**Issue by fmsan51** [sethyuan/logseq-plugin-charspacing#9]
It would be great the plugin could add a space between Latin characters and Japanese Hiragana/Katakana (\u3040-\u30FF) as well as Chinese characters.

**Comment by sethyuan** [comment]
I added the Unicode range you gave me. Please update and give it try.

**Comment by fmsan51** [comment]
I tried v1.2.0 and it worked well. Thank you!
